name: 缺少音源提醒

on:
  issue_comment:
    types: [created]  # 监听评论创建事件

jobs:
  add-slowqueue-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get repository collaborators
        id: get-collaborators
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取所有仓库协作者的 GitHub 用户名
          collaborators=$(gh api repos/${{ github.repository }}/collaborators --jq '.[].login' | tr '\n' ' ')
          echo "collaborators=$collaborators" >> $GITHUB_ENV

      - name: Add "缺少音源" label if "!noaudio" command is used
        if: |
          github.event.issue.pull_request &&
          contains(github.event.comment.body, '!noaudio') &&
          env.collaborators != '' &&
          env.collaborators =~ github.actor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Adding '缺少音源' label to PR #${{ github.event.issue.number }}"
          gh pr edit ${{ github.event.issue.number }} --add-label "缺少音源"

      - name: Auto reply to PR with preset message
        if: |
          github.event.issue.pull_request &&
          contains(github.event.comment.body, '!noaudio') &&
          env.collaborators != '' &&
          env.collaborators =~ github.actor
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Replying to PR #${{ github.event.issue.number }}"
          COMMENT_BODY="您好，您的投稿缺少对应音源，请向我们提供与之对应的音源以便审核，感谢您对本项目的支持！"
          gh pr comment ${{ github.event.issue.number }} --body "$COMMENT_BODY"
